### PR TITLE
Improve documentations

### PR DESCRIPTION
**Pull request by Jean-BaptisteC**
- Update readme
- Add release documentation
- Remove trigger workflow when user pushes change in doc directory

### CODE REVIEW

**Comment by codeurimpulsif** [comment]
Why renaming `doc` to `docs`?

**Comment by Jean-BaptisteC** [comment]
Because we have several docs not just one

**Comment by codeurimpulsif** [comment]
Naming a documentation directory (and all directories in general) using the singular is a best practice and is also how we named other documentations directories, so I think `doc` is a better name

**Comment by Jean-BaptisteC** [comment]
Branch rebased and changes about directory reverted

**Review by codeurimpulsif — APPROVED** [review]
Thanks, it's ok for me!

**Pull request merged**
