### PR TITLE
Introduce About Fragment

### PR DESCRIPTION
**Pull request by theimpulson**
This MR:

- Upstreams the Gradle and dependencies to the latest stable release
- Adds a new About Fragment which displays app logo, description, and privacy policy URL (not hosted on the server yet)

This should close https://github.com/Exodus-Privacy/exodus-android-app/issues/111, however, keep in mind that the URL seems not hosted or public yet and should be handled as well.

The URL can be changed by maintainers by editing the variable value in `app/src/main/java/org/eu/exodus_privacy/exodusprivacy/fragments/AboutFragment.java`

### CODE REVIEW

**Comment by theimpulson** [comment]
The `ic_information` vector drawable has been taken from [materialdesignicons](https://materialdesignicons.com/).

**Comment by Jean-BaptisteC** [comment]
Request changes:
- Change privacy policy string like others links on app (in exodus app on purple, we don't see difference between purple and black)
- Hide search button and filter button on about ihm like trackers ihm

**Comment by Jean-BaptisteC** [comment]
On smartphone in mode landscape, we don't see privacy policy string

**Comment by Jean-BaptisteC** [comment]
Ok for me, i have tested changes:

- No regression
- No new bugs

**Pull request merged**
