### PR TITLE
Improve tracker and permission chip

### LINKED ISSUE #242: Improve trackers and permissions chip
Some users don't understand icon behind number in chip, i suggest to update this:

- [ ] Add trackers and permission text after number
- [ ] On all fragments
Some design:

### PR DESCRIPTION
**Pull request by Jean-BaptisteC**
Closes #242
I have update tracker and permission chip for better comprehension
I need feedback on UI

### CODE REVIEW

**Comment by pnu-s** [comment]
@Jean-BaptisteC Could you post screenshots of the UI before/after the change?

I'm not sure how it looks currently :smile:

**Comment by Jean-BaptisteC** [comment]
You can check screenshots in readme to compare :)

**Comment by pnu-s** [comment]
Didn't we get UI models for the android app? I'm not sure what is the purpose of the change here and where does it come from.

Note that I don't have any expertise in UI or UX :)

**Comment by Jean-BaptisteC** [comment]
To your give more details:
- In 2.0, we show in app, trackers and permissions numbers like this [number in square with background color following value number] + permissions or trackers strings
- In 3.0, we show in app, trackers and permissions numbers like this [icon + number in square with background color following value number]
During the development of 3.0 version, I have doing UI models but following first mock of dev.
I agree icon is not enough clear to tell what is permission, what is tracker. That's why I suggest these changes to improve comprehension of information in app

|v2|v3|New changes|
|-|-|-|
||||

**Comment by Jean-BaptisteC** [comment]
To give you more details about code changes:
- Refactor setExodusColor function
  - Replace int parameter by a string parameter to improve the case if we don't have reports on the app and we show a `?`
  - Replace condition to check if the string is a number instead of check if the string is `?`
  - Init textColorStateList and backgroundColorStateList values at the start to reduce assignations
  - Remove assignation to update the color icon in the chip
- Number of permissions and number of trackers are now converted to a string to simplify code
- In AppDetailFragment, remove chips (present below app icon) containing number of permissions and number of trackers because this information was already present in tabs and update constraints between elements in the layout.
- In recycler view app item (used foreach items in app list), add new strings (permissions and trackers strings), improve constraint to be sure margin is enough between chips and texts and to be sure text doesn't mask other elements.
- Remove in other layouts properties to set icon chip and icon chip color
- Reduce border radius of chip

**Review by codeurimpulsif — APPROVED** [review]
Can't review the code but I approve for the concept

**Pull request merged**
