### PR TITLE
Issue 244

### PR DESCRIPTION
**Pull request by PatDyn**
Should resolve Issue #244 
* Remove startForeground() from ExodusUpdateService
* Remove foreground Permission
* Make ExodusUpdateService private
  * by setting android:exported "false"
* Add tests for ExodusUpdateService being started
  * add method allowing access to IS_SERVICE_STARTED
  * create test scope and test coroutines
* Fix extra IO dispatcher in ExodusAPIRepository

### CODE REVIEW

**Comment by Jean-BaptisteC** [comment]
Failed to get app details, response code: 401

**Comment by Jean-BaptisteC** [comment]
Why button to cancel refresh in notification have disappear ?

**Review by Jean-BaptisteC — APPROVED** [review]
✅ Pixel 6 - Android 13
Have you need to declare REORDER_TASK permission in manifest ?

**Comment by PatDyn** [comment]
> REORDER_TASK
I'm not aware of any parts of our code changing task order. 
So I did not declare this in the manifest. Do you think this might be an issue?

**Comment by Jean-BaptisteC** [comment]
I guess REORDER TASK permission is used by dispatcher

**Comment by Jean-BaptisteC** [comment]
I didn't have find information about this permission, REORDER Tasks permission is already on master, this permission was introduced when you have add dispatcher.

**Pull request merged**
