### PR TITLE
Create strings.xml PL

### PR DESCRIPTION
**Pull request by phyrz91**
Polish translation.

Ps. Please update the app icon according to Material You(monet theme).

### CODE REVIEW

**Comment by Jean-BaptisteC** [comment]
Thanks,

- Can you update your branch ?
- Add translation for this new string https://github.com/Exodus-Privacy/exodus-android-app/blob/f88d9427361dfde2be9f727ac22d7d419d5136cc/app/src/main/res/values/strings.xml#L44
- Add here https://github.com/Exodus-Privacy/exodus-android-app/blob/master/app/src/main/res/xml/locales_config.xml
`<locale android:name="pl"/> <!-- Polish -->` to able to choose app language

Themed icon is supported in latest version here https://github.com/Exodus-Privacy/exodus-android-app/releases/tag/release-v3.1.0

**Comment by phyrz91** [comment]
Hi.

Done.

Regards.

**Comment by Jean-BaptisteC** [comment]
@phyrz91 short_description is too long (max 80 characters)
Can you create new PR to fix this ?

**Comment by phyrz91** [comment]
Done.

**Pull request merged**
