### PR TITLE
Add Obtainium badge

### PR DESCRIPTION
**Pull request by Jean-BaptisteC**
I have discovered recently [Obtainium](https://github.com/ImranR98/Obtainium), this app adds the ability to update your apps by listening to new versions in Github.

It's very easy to use and used by a lot of open-source projects.
I suggest adding a badge in readme

[Exodus report](https://reports.exodus-privacy.eu.org/fr/reports/449542/)

Todo
- [x] Fix size of badge

### CODE REVIEW

**Comment by codeurimpulsif** [comment]
So it's an app that download APK and install it?

**Comment by Jean-BaptisteC** [comment]
Yes, exactly

**Review by codeurimpulsif — APPROVED** [review]
ok, I approve it, just need to change the size

**Comment by Jean-BaptisteC** [comment]
I have fixed badges.
I have also create PR on this [repository](https://github.com/ImranR98/apps.obtainium.imranr.dev), to see app on [apps store](https://apps.obtainium.imranr.dev/)

WDYT to push information on Mastodon?

**Pull request merged**
