### PR TITLE
Release 3.3.0

### PR DESCRIPTION
**Pull request by Jean-BaptisteC**
~~Require #437 to be merged~~
Closes #424

~~I have planned to generate new screenshots before merge~~

### CODE REVIEW

**Comment by Jean-BaptisteC** [comment]
Release is ready to be merge

**Comment by codeurimpulsif** [comment]
Hi @Jean-BaptisteC

I don't understand why you delete this translations:
- no_app_found
- no_settings
- logo
- refresh_needed
- refresh_needed_message
- submit
- app_not_analyzed
- app_not_analyzed_title

Did we still have this functionnalities?

**Comment by Jean-BaptisteC** [comment]
These translations are not used anymore because we use new translations.
And you are right some translations have been used in the past in features not reimplemented in the 3.0 version, because features are not enough helpful for users:
- In the past, we had a feature to get app reports from Android menu share, but nobody knew this feature and you can do the same thing with the platform, and reimplementing this feature is really a constraint with last versions of Android (Android control each app started in the background and can kill activity of service when he wants).
- And before we have a pop-up that appears when you start the app regularly to suggest to refresh reports -> it's too invasive for users.

**Review by codeurimpulsif — APPROVED** [review]
Seems ok for me, thanks you!

**Comment by Jean-BaptisteC** [comment]
I push the tag tonight

**Pull request merged**
