### PR TITLE
fixed issue: migrate to ksp annotation processor

### PR DESCRIPTION
**Pull request by Nassr-Allah**
#322 
- Added the version and lib in lib.versions.toml
- Replaced kapt with ksp
- Replaced javaCompileOptions with ksp
- Added type converter for MutableList<String>
- Passed an instance of the type converters class to the Room Database Builder

### CODE REVIEW

**Review by Jean-BaptisteC — APPROVED** [review]
Thanks,
Can you remove useless comma (Linter doesn't like comma after last parameter) ?

**Comment by Nassr-Allah** [comment]
Useless Commas have been removed

**Comment by Jean-BaptisteC** [comment]
Can you fix ExodusDatabaseRepositoryTest ?
```
kotlin.UninitializedPropertyAccessException: lateinit property testDB has not been initialized
at org.eu.exodus_privacy.exodusprivacy.ExodusDatabaseRepositoryTest.teardown(ExodusDatabaseRepositoryTest.kt:136)
```

**Comment by Nassr-Allah** [comment]
ExodusDatabaseRepositoryTest has been fixed

**Comment by Jean-BaptisteC** [comment]
Can you remove unused import in Test?

Pixel 6 - Android 13
Tests ✅

**Pull request merged**
