### PR TITLE
ci: Scan with exodus-standalone 

### LINKED ISSUE #134: Add exodus-standalone to Github Actions
I think we could scan the built application with GitHub Actions with https://github.com/Exodus-Privacy/exodus-standalone for each merge request.

This would:
* make sure that we do not add any tracker
* do what we recommend to others :)
* probably add a new example into exodus-standalone documentation

### PR DESCRIPTION
**Pull request by pnu-s**
### Content

Fixes #134 

Adds a new step to GitHub Actions to scan the generated apk with [exodus-standalone](https://github.com/Exodus-Privacy/exodus-standalone)

### Todo

- [x] Update exodus-standalone README with this example -> https://github.com/Exodus-Privacy/exodus-standalone/pull/39

### CODE REVIEW

**Comment by Jean-BaptisteC** [comment]
You can just use
run: |
     docker run -v $(pwd)/app/build/outputs/apk/exodus/release/app-exodus-release-unsigned.apk:/app.apk --rm -i exodusprivacy/exodus-standalone

It's more easy and we have not need update file foreach exodus-standalone update

**Comment by pnu-s** [comment]
> It's more easy

I'm not sure to agree here, I find my proposal more standard with GitHub Actions.

> we have not need update file foreach exodus-standalone update

I don't understand this part, could you please elaborate? :)

**Comment by Jean-BaptisteC** [comment]
Ok as you want

With docker run, he takes latest version
With your solution, you need to update workflow, when your create a new release of Exodus-standalone

**Comment by pnu-s** [comment]
>  With your solution, you need to update workflow, when your create a new release of Exodus-standalone

No we don't **need** to, we just control the version we are using.
As long as the current version fits our needs, we can keep it, we do not need to always get the latest version.

See https://cloudmaniac.net/docker-container-never-use-latest-cicd-pipeline/ for an example of why to not use the `latest` tag.

**Review by Jean-BaptisteC — APPROVED** [review]

**Pull request merged**
