### PR TITLE
Issue 260

### PR DESCRIPTION
**Pull request by PatDyn**
This should somewhat mitigate or even solve Issue #260 and #264.
It may even improve first startup performance a little bit.

What changed:
* Add a sequence diagram of the old architecture in doc
* Reduce amount of calls to the PackageManager
* Move the calculation of the packageName to view time
  * calculate the name without a regex
* Refactor ExodusUpdateService and PackageManagerModule (PMM)
  * add a ExodusPackageRepository
  * move most of functionality from PMM to there
  * move most of the list operations off the main thread
  * only generate the validPackages list on the main thread
    * as this is immediately needed for the apps operation
* Implement tests accordingly

### CODE REVIEW

**Comment by Jean-BaptisteC** [comment]
Wrong regex on short permission:
Full permission:
- com.android.vending.p2p.APP_INSTALL_API
Short permission:
- 2p.APP_INSTALL_API
Full permission:
- com.x8bit.bitwarden.DYNAMIC_RECEIVER_NOT_EXPORTED_PERMISSION
Short permission:
- 8bit.bitwarden.DYNAMIC_RECEIVER_NOT_EXPORTED_PERMISSION
Full permission:
- Com.google.restricted_assist_gesture.permission.RESTRICTED_ASSIST_GESTURE_PROVIDER
Short permission:
- _assist_gesture.permission.RESTRICTED_ASSIST_GESTURE_PROVIDER

**Comment by PatDyn** [comment]
> Permissions is not order by alphabetically I have ANR on app after consult permissions about Services Google Play (323 permissions) Edit: ANR is not reproduced with apk without network local config

I guess the ANR was actually caused by computing the name on view time. My bad.
I moved it back to the PackageRepository and added a shortName and longName properties to the permission data class.

**Comment by PatDyn** [comment]
> Wrong regex on short permission: Full permission:
> 
>     * com.android.vending.p2p.APP_INSTALL_API
>       Short permission:
> 
>     * 2p.APP_INSTALL_API
>       Full permission:
> 
>     * com.x8bit.bitwarden.DYNAMIC_RECEIVER_NOT_EXPORTED_PERMISSION
>       Short permission:
> 
>     * 8bit.bitwarden.DYNAMIC_RECEIVER_NOT_EXPORTED_PERMISSION
>       Full permission:
> 
>     * Com.google.restricted_assist_gesture.permission.RESTRICTED_ASSIST_GESTURE_PROVIDER
>       Short permission:
> 
>     * _assist_gesture.permission.RESTRICTED_ASSIST_GESTURE_PROVIDER

This is fixed now - turns out the regex can not be fully avoided. But the complicated regex will now only be used in special cases.

**Review by Jean-BaptisteC — APPROVED** [review]
✅ Pixel 6 - Android 13
Order permissions ✅
Regex ✅

Please rebase branch

**Comment by PatDyn** [comment]
> white_check_mark Pixel 6 - Android 13 Order permissions white_check_mark Regex white_check_mark
> 
> Please rebase branch

Rebase is done.

**Pull request merged**
