### PR TITLE
Issue 176

### PR DESCRIPTION
**Pull request by PatDyn**
Should resolve Issue #176 
* Adds more logging to ADTrackersFragment and TrackersRVAdapter
* We now explicitly count the number of Apps having trackers on the phone
    * There is also a simple test for this logic
* The DB Schema for the TrackerData entity is updated to hold this number
* To accomodate these changes for users, a database migration has been implemented
    * the database migration is also tested

### CODE REVIEW

**Comment by Jean-BaptisteC** [comment]
What about performance ?
Because, when report have a lot of permission, app is slow

**Comment by PatDyn** [comment]
> What about performance ? Because, when report have a lot of permission, app is slow

Can you elaborate on that? The code i changed does not touch the permissions list of neither AppDetails() or ExodusApplication().

**Comment by Jean-BaptisteC** [comment]
New management about database have a difference about performance ?
Yes i know, you don't have changed how information is get
I want know if this migration to new management have impact of performance because i know our app have not a best performance and reports with lots of permission can create lag on app

**Comment by PatDyn** [comment]
> New management about database have a difference about performance ? Yes i know, you don't have changed how information is get I want know if this migration to new management have impact of performance because i know our app have not a best performance and reports with lots of permission can create lag on app

Ok, i see. There should not be a noticeable impact on performance. I only added one column in TrackerData. The migration is just a tool to make this work, when the app is updated on phones already hosting a filled database.

**Review by Jean-BaptisteC — APPROVED** [review]
✅ Pixel 6 - Android 13

**Pull request merged**
