### PR TITLE
Fixes #239(Theme option) 

### LINKED ISSUE #239: Add setting to change color theme
### Discussed in https://github.com/Exodus-Privacy/exodus-android-app/discussions/162

<div type='discussions-op-text'>

<sup>Originally posted by **Jean-BaptisteC** May 11, 2022</sup>
On about_fragment, at the top left

- Add [icon more](https://fonts.google.com/icons?selected=Material%20Icons%20Outlined%3Amore_vert%3A) to give access on theme settings
- Add pop-up to select color theme
Screenshot 2022-05-11 at 21-34-18 Figma
- Option default is System Default
 </div>

### PR DESCRIPTION
**Pull request by StellarSand**
As discussed in #309 splitting theme into a separate PR. Haven't added checkbox yet.

### CODE REVIEW

**Comment by Jean-BaptisteC** [comment]
Did you have need help to continue PR ?
Is it more easy for you, if we drop API 21 and API 22 ?

**Comment by the-weird-aquarian** [comment]
Hi. I was little busy with other things and hence could not continue. I will implement the checkbox tomorrow. If all works well there's no need to drop support for API 21 & 22. If not, we'll think about it later. I guess the only help needed is implementing preferences wherever I've added `TODO` comments. Will let you know after I try tomorrow.

**Comment by Jean-BaptisteC** [comment]
Ok,
To implement preferences, you can check PR #273

**Comment by the-weird-aquarian** [comment]
Switch :heavy_check_mark: 
OK button :heavy_check_mark: 
Icon :heavy_check_mark: 
preferences :x:

**Comment by Jean-BaptisteC** [comment]
To implement preferences, you can find more information here
https://developer.android.com/topic/libraries/architecture/datastore
https://medium.com/androiddevelopers/datastore-and-dependency-injection-ea32b95704e3

I think to start implementation, you need to add a new default value here:
https://github.com/Exodus-Privacy/exodus-android-app/blob/78f5d380d42a63ff60b1638e8ea74c84b97af1a7/app/src/main/java/org/eu/exodus_privacy/exodusprivacy/manager/storage/ExodusDataStoreRepository.kt#L33

To check value, you can check this function https://github.com/Exodus-Privacy/exodus-android-app/blob/78f5d380d42a63ff60b1638e8ea74c84b97af1a7/app/src/main/java/org/eu/exodus_privacy/exodusprivacy/MainActivity.kt#L97

To update value, you can check this https://github.com/Exodus-Privacy/exodus-android-app/blob/78f5d380d42a63ff60b1638e8ea74c84b97af1a7/app/src/main/java/org/eu/exodus_privacy/exodusprivacy/MainActivityViewModel.kt#L27

**Comment by Jean-BaptisteC** [comment]
Is it easier for you, if we use android x preference?

**Comment by StellarSand** [comment]
Hello. I've been very busy and unwell recently. I'll take a look at this once I recover soon.

**Pull request closed without merging**
