### PR TITLE
Release v2.2.1

### PR DESCRIPTION
**Pull request by Jean-BaptisteC**
- [x]  Bump Target SDK Version to 31 + add android:exported="true" to allow activties execution
- [x] Fix translations (en-US/fr-FR)
- [x] Add icon in metadata folder
- [x] Add changelog (en-US/fr-FR)
- [x] Update version code and version name
- [x] Remove version Google / Fdroid (one version for all stores)

### CODE REVIEW

**Comment by pnu-s** [comment]
I'm not sure to be able to review everything to be honest.

@theimpulson do you have any input on this? :pray: 
Thanks!

**Review by theimpulson — APPROVED** [review]

**Comment by theimpulson** [comment]
Looks fine to me, lgtm

**Comment by pnu-s** [comment]
Do we need to do https://github.com/Exodus-Privacy/exodus-android-app/issues/140 before?

**Comment by theimpulson** [comment]
> Do we need to do #140 before?

@pnu-s nope, that's not a blocker for this PR and can be done later on.

**Comment by Jean-BaptisteC** [comment]
@theimpulson Can you give me a feedback on the last commits

**Comment by pnu-s** [comment]
Thanks @Jean-BaptisteC for all these changes! :+1: 

Small note, when possible, please try to prefer doing smaller PR, so that:
1) it's easier to review and to merge
2) it's clearer in the commits what really changed

**Review by theimpulson — APPROVED** [review]
New changes look fine. Tested the generated artifact, works fine for me. Approved!

**Comment by Jean-BaptisteC** [comment]
Tested on Pixel 6 (Android 12 SDK31)
- No regression :white_check_mark:
- No new bugs :white_check_mark:

**Pull request merged**
