### PR TITLE
Fixing overflow of numbers

### LINKED ISSUE #42: Display bug with 100+ permissions
This sounds silly, but "Google Play services" is shown as an app with 197 permissions on the Exodus Privay application, which does not display properly with the new colored buttons. See below:

#### Screenshot1:
image

#### Screenshot2:
image

### PR DESCRIPTION
**Pull request by Mineroboter**
Fixes #42

### CODE REVIEW

**Comment by Schoumi** [comment]
thanks for your work. I'll merge it tomorrow.

**Comment by Mineroboter** [comment]
Note: This only fixes the part of issue #42 named "Screenshot1". The fragment layout of "Screenshot2" still needs to be changed separately in another xml.

**Comment by Mineroboter** [comment]
I fixed also now the fragment layout in "Screenshot2".

**Comment by Schoumi** [comment]
thanks for the contribution

**Pull request merged**
